<?php

namespace LAP\BlogBundle\Entity;
namespace LAP\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
	public function findArticles()
	{
		$qb = $this->createQueryBuilder('a');
		
		$qb
			->where( 'a.datePub <= :dateJour' )
			->setParameter( 'dateJour', new \Datetime() )
			->andWhere( 'a.active = :isActive' )
			->setParameter( 'isActive', 1 )
			->orderBy( 'a.datePub', 'DESC' )
		;
		
		$query = $qb->getQuery();
		
		$results = $query->getResult();
		
		return $results;
	}
	
	public function findAllarticles($limit)
	{
		$qb = $this->createQueryBuilder('a');
		
		$qb->setMaxResults($limit);
		$qb->orderBy( 'a.dateCrea', 'DESC' );
		
		$query = $qb->getQuery();
		
		$results = $query->getResult();
		
		return $results;
	}
}
