<?php

namespace LAP\TodoBundle\Repository;

/**
 * TodolistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodolistRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAlltasks($idusr, $limit) { // $limit = 0 => no limit
		$query = $this->_em->createQuery('SELECT a.id AS id, a.titre AS titre, a.dateCrea AS dateCrea, a.dateFin AS dateFin, a.auteur AS auteur, a.isdone AS isdone, a.forall AS forall, u.username AS username FROM LAPTodoBundle:Todolist a LEFT JOIN LAPUtilisateurBundle:User u WITH (a.auteur = u.id) WHERE a.forall = :forall OR a.auteur = :idusr ORDER BY a.dateCrea ASC')
			->setParameter('forall', 1)
			->setParameter('idusr', $idusr);

		if($limit > 0) {
            $query->setMaxResults($limit);
        }
		$results = $query->getResult();

		/* Calculation of the difference between 'now' date and dateFin */

        $nowDate = new \DateTime();
        $nowDate->setTime(00, 00);

		foreach($results as $key => $value) {
            $finalDate = $results[$key]['dateFin'];
            $interval = $finalDate->diff($nowDate);
            $difference = $interval->format('%R%a');
		    $results[$key]['intervall'] = $difference;
        }
        //die(var_dump($finalDate).'|'.var_dump($nowDate).'|'.$difference);
		
		return $results;
	}
}
