<?php

namespace LAP\UtilisateurBundle\Repository;

/**
 * AdminrolesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminrolesRepository extends \Doctrine\ORM\EntityRepository
{
}
