<?php

namespace LAP\UtilisateurBundle\Entity;
namespace LAP\UtilisateurBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{	
	public function findAllusers()
	{
		$qb = $this->createQueryBuilder('a');
		
		$qb
			->where( 'a.active = :activetrue' )
			->setParameter( 'activetrue', 1 )
			->orderBy( 'a.dateCrea', 'DESC' )
			->setMaxResults(10)
		;
		
		$query = $qb->getQuery();
		
		$results = $query->getResult();
		
		return $results;
	}
	
	public function findUser($id)
	{
		$qb = $this->createQueryBuilder('a');
		
		$qb
			->where( 'a.id = :id' )
			->setParameter( 'id', $id )
			->setMaxResults(1)
		;
		
		$query = $qb->getQuery();
		
		$results = $query->getResult();
		
		return $results;
	}
	
	public function findAllonsite()
	{
		$qb = $this->createQueryBuilder('a');
		
		$qb
		  ->where('a.onsite = :os')
		  ->setParameter('os', 1);
		  
		return $qb->getQuery()->getResult();
	}
}
