<?php

namespace LAP\MessagerieBundle\Repository;

/**
 * MessagerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessagerieRepository extends \Doctrine\ORM\EntityRepository
{
	public function findMymessages($idDest)
	{
		/*$qb = $this->createQueryBuilder('a');
		
		$qb
			->where( 'a.idDestinataire = :iddest' )
			->setParameter( 'iddest', $idDest )
			->orderBy( 'a.dateReception', 'DESC' )
		;
		
		$query = $qb->getQuery();*/
		
		$query = $this->_em->createQuery('SELECT a.id AS id, a.titre AS titre, a.dateReception AS dateReception, a.texte AS texte, a.lu AS lu, u.username AS username FROM LAPMessagerieBundle:Messagerie a LEFT JOIN LAPUtilisateurBundle:User u WITH (a.idAuteur = u.id) WHERE a.idDestinataire = :iddest ORDER BY dateReception DESC')
			->setParameter('iddest', $idDest);
		
		$results = $query->getResult();
		
		return $results;
	}
	
	public function findLastmessages($idDest, $limit)
	{		
		$query = $this->_em->createQuery('SELECT a.id AS id, a.titre AS titre, a.dateReception AS dateReception, a.texte AS texte, a.lu AS lu, u.username AS username, u.picture AS picture FROM LAPMessagerieBundle:Messagerie a LEFT JOIN LAPUtilisateurBundle:User u WITH (a.idAuteur = u.id) WHERE a.idDestinataire = :iddest AND a.lu = 0 ORDER BY dateReception DESC')
			->setParameter('iddest', $idDest)
			->setMaxResults($limit);
		
		$results = $query->getResult();
		
		return $results;
	}
	
	public function findMessage($id)
	{
		$query = $this->_em->createQuery('SELECT a.id AS id, a.titre AS titre, a.dateReception AS dateReception, a.texte AS texte, a.lu AS lu, a.dateLecture AS dateLecture, u.username AS username, u.id AS idusername FROM LAPMessagerieBundle:Messagerie a LEFT JOIN LAPUtilisateurBundle:User u WITH (a.idAuteur = u.id) WHERE a.id = :id')
			->setParameter('id', $id)
			->setMaxResults(1);

		$results = $query->getSingleResult();
		
		return $results;
	}
}
