<?php

namespace LAP\CalendarBundle\Repository;

/**
 * EventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventsRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllCalendar()
	{
		return $this->createQueryBuilder('a')->getQuery()->getArrayResult();
	}
	
	public function findEvent($id)
	{
		$query = $this->_em->createQuery('SELECT a.id AS id, a.title AS title, a.start AS startDate, a.end AS endDate, a.dateCrea AS dateCrea, a.texte AS texte, a.startHour AS startHour, a.endHour AS endHour, u.username AS username FROM LAPCalendarBundle:Events a LEFT JOIN LAPUtilisateurBundle:User u WITH (a.auteur = u.id) WHERE a.id = :id')
			->setParameter('id', $id);
		
		$results = $query->getResult();
		
		return $results;
	}
	
	public function findLastCalendarid()
	{
		$qb = $this->createQueryBuilder('a')
			->orderBy('a.id', 'DESC')
			->setMaxResults(1);
		$results = $qb->getQuery()->getSingleResult();
		return $results;
	}
}
