services:
    lap_blog.closetags:
        class: LAP\BlogBundle\Closetags\LAPClosetags
#    lap_blog.example:
#        class: LAP\BlogBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
