<?php

namespace LAP\NotificationsBundle\Repository;

/**
 * NotificationsstatutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationsstatutRepository extends \Doctrine\ORM\EntityRepository
{
}
