<?php

namespace LAP\NotificationsBundle\Repository;

/**
 * NotificationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationsRepository extends \Doctrine\ORM\EntityRepository
{
	public function findLastnotifications($limit)
	{
		$query = $this->_em->createQuery('SELECT a.id AS id, a.titre AS titre, a.dateNotif AS dateNotif, a.texte AS texte, a.statut AS statut, u.username AS username, v.status AS statutname FROM LAPNotificationsBundle:Notifications a LEFT JOIN LAPUtilisateurBundle:User u WITH (a.auteur = u.id) LEFT JOIN LAPNotificationsBundle:Notificationsstatut v WITH (a.statut = v.id) ORDER BY dateNotif DESC')
			->setMaxResults($limit);
		
		$results = $query->getResult();
		
		return $results;
	}
	
	public function findAllnotifications()
	{
		$query = $this->_em->createQuery('SELECT a.id AS id, a.titre AS titre, a.dateNotif AS dateNotif, a.texte AS texte, u.username AS username, v.id AS idStatut, v.status AS statut FROM LAPNotificationsBundle:Notifications a LEFT JOIN LAPUtilisateurBundle:User u WITH (a.auteur = u.id) LEFT JOIN LAPNotificationsBundle:Notificationsstatut v WITH (a.statut = v.id) ORDER BY dateNotif DESC');
		
		$results = $query->getResult();
		
		return $results;
	}
	
	public function findNotification($id)
	{
		$query = $this->_em->createQuery('SELECT a.id AS id, a.titre AS titre, a.dateNotif AS dateNotif, a.texte AS texte, u.username AS username, v.id AS idStatut, v.status AS statut FROM LAPNotificationsBundle:Notifications a LEFT JOIN LAPUtilisateurBundle:User u WITH (a.auteur = u.id) LEFT JOIN LAPNotificationsBundle:Notificationsstatut v WITH (a.statut = v.id) WHERE a.id = :id')
			->setParameter('id', $id)
			->setMaxResults(1);
		
		$results = $query->getSingleResult();
		
		return $results;
	}
}
